### ISSUE TITLE
how can i using the code with my own model and algrothem??

### ISSUE THREAD

**Issue by henbucuoshanghai** [Rapternmn/PyTorch-Onnx-Tensorrt#10]

**Comment by Rapternmn** [comment]
Hii, generally for any model, the standard procedure is to convert the torch model to onnx and then to TRT Engine. But Incase of Yolov3, this conversion was not so straightforward.

**Comment by henbucuoshanghai** [comment]
&nbsp;the standard procedure is to convert the torch model to onnx and then to TRT Engine



how？&nbsp; where is lessons i can learn？
