### ISSUE TITLE
ModuleNotFoundError: No module named 'darknet'

### ISSUE THREAD

**Issue by gillmac13** [Rapternmn/PyTorch-Onnx-Tensorrt#4]
Sorry, I have not found this resource. 
Any easy way to find it ? Thanks in advance.
I am very much interested in your project, there are not many solutions able to convert yolov3 models to onnx and rt. I hope this repo works !

**Comment by Rapternmn** [comment]
@gillmac13 
Hey Man, Thanks for bringing this to notice. I had apparently forgotten to include this file in the repo.
Do pull it again and try out the demos. Let me know if there are any other issues.
